cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'pyenv'
brew 'openssl'
brew 'nvm'
brew 'readline'
brew 'wget'
brew 'neovim'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'ffmpeg'
brew 'jq'
brew 'nmap'
brew 'tree'

cask 'dropbox'
cask '1password'
cask 'iterm2'
cask 'slate'
cask 'visual-studio-code'
cask 'karabiner-elements'
cask 'spotify'
cask 'steam'
cask 'docker'
cask 'discord'
cask 'vlc'
cask 'alfred'
